import { HttpException } from '@exceptions';

import MESSAGES from './messages';

const { BAD_REQUEST, USERNAME_EXISTS, USERNAME_NO_EXISTS, SERVICE_UNAVAILABLE, INVALID_PASSWORD } =
  MESSAGES.ERROR;

export default {
  BAD_REQUEST_EXCEPTION: new HttpException(BAD_REQUEST.CODE, BAD_REQUEST.MESSAGE),
  USERNAME_EXISTS_EXCEPTION: new HttpException(USERNAME_EXISTS.CODE, USERNAME_EXISTS.MESSAGE),
  USERNAME_NO_EXISTS_EXCEPTION: new HttpException(
    USERNAME_NO_EXISTS.CODE,
    USERNAME_NO_EXISTS.MESSAGE
  ),
  SERVICE_UNAVAILABLE_EXCEPTION: new HttpException(
    SERVICE_UNAVAILABLE.CODE,
    SERVICE_UNAVAILABLE.MESSAGE
  ),
  INVALID_PASSWORD_EXCEPTION: new HttpException(INVALID_PASSWORD.CODE, INVALID_PASSWORD.MESSAGE),
};
